### ISSUE TITLE
A bug in ./pkg/base/install.sh

### ISSUE THREAD

**Issue by gouwh29** [djhshih/patefiant#1]
In this script, the `ROOT` variable (line 4) is not setup correctly if you specify a customised install path:

Original code:

```
export ROOT=${ROOT:-$HOME/local}
```

Need to be changed to:
```
export ROOT=${ROOT:-$DESTDIR}
```

To include the `DESTDIR` variable defined in `./install.sh` (line 7)
```bash
export DESTDIR=${DESTDIR:-$HOME/local}
```

**Comment by djhshih** [comment]
Thanks. Fixed in d72e4bb3d4181f2a14852d526f83774603e9d320
